(* PROBLEM --
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7^(th) triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
 * first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 *
 * SOLUTION --
 *
 * tri(n) = n * (n+1) / 2
 *
 * As n and n+1 are coprime, then either n/2 and n+1 are coprime integers
 * or n and (n+1)/2 are.
 *
 * if n and m are coprime, then as they share no common factor other than 1,
 * d(nm) = d(n) * d(m)
 *
 * Also d(n) is an element of the sequence [1,n].
 *)

open Numbers

let divisors n =
  let rec helper x divs =
    if x = n then n::divs
    else if x || n then helper (succ x) (x::divs)
    else helper (succ x) divs
  in helper 1 []

let d_tri n =
  let x,y = if 2 || n then (n/2),(n+1) else n,(n+1)/2 in
  List.length(divisors x) * List.length(divisors y)

let search_d_tri lbd =
  let rec helper n = if d_tri n > lbd then n else helper (succ n) in
  helper 1

let main () =
  let n = search_d_tri 500 in
  print_int(tri_num n);
  print_newline();;

main();;
