(* PROBLEM --
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 * Triangle       T_(n)=n(n+1)/2      1, 3, 6, 10, 15, ...
 * Pentagonal       P_(n)=n(3n−1)/2       1, 5, 12, 22, 35, ...
 * Hexagonal      H_(n)=n(2n−1)       1, 6, 15, 28, 45, ...
 *
 * It can be verified that T_(285) = P_(165) = H_(143) = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * SOLUTION --
 * Since T(2n-1) = H(n), ignore H(n) and even index T(n).
 *)
let tri n = n*.(n+.1.)/.2.

let is_pent x =
  let nf = (sqrt(24.0*.x+.1.0)+.1.0)/.6.0 in
  let n = truncate nf in
  nf -. (float n) < epsilon_float

let search limit =
  let rec helper i count =
    if count > 0 then
    let t = tri i in
    if t < 0. then failwith ("Overflow:"^(string_of_float i))
    else if is_pent t then
      (Printf.printf "(%.0f,%.0f)\t" i t; helper (i+.2.) (count-1))
    else helper (i+.2.) count
  in (helper 1.0 limit; print_newline())

let _ = search 3;;
